{{- range $nsPrefix := .Values.secrets.namespacePrefixes }}
{{- range $item := $.Values.secrets.items }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $item.name }}
  namespace: {{ $nsPrefix }}-{{ $.Values.environment }}
spec:
  itemPath: {{ $item.itemPath }}
---
{{- end}}
{{- end}}