{{- range $item := $.Values.secrets.items }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $item.name }}
  namespace: {{ $item.namespace }}
spec:
  itemPath: {{ $item.itemPath }}
---
{{- end}}